#!/usr/bin/env bash

# Comments to support chkconfig on RedHat Linux
# chkconfig: 2345 99 99
# description: A program to gather large amounts of data durning mysql issues.

### BEGIN INIT INFO
# Provides:          pt-stalk
# Required-Start:    $network $named $remote_fs $syslog
# Required-Stop:     $network $named $remote_fs $syslog
# Should-Start:      pt-stalk
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO                                                                                                                                          

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME="pt-stalk"
DESC="pt-stalk"
DAEMON="/usr/bin/$NAME"
PIDFILE="/var/run/${NAME}.pid"
CONFIGFILE="/etc/percona-toolkit/${NAME}.conf"
[ -r /etc/default/$NAME ] && . /etc/default/$NAME
DAEMON_OPTS="--config $CONFIGFILE --daemonize --pid $PIDFILE"
STALKHOME="/var/lib/pt-stalk"

test -x $DAEMON || exit 0

#
# Use LSB init script functions for printing messages, if possible
#
lsb_functions="/lib/lsb/init-functions"
if test -f $lsb_functions ; then
  . $lsb_functions
else
  log_success_msg()
  {
    echo " SUCCESS! $@"
  }
  log_failure_msg()
  {
    echo " ERROR! $@"
  }
fi

sig () {
    test -s "$PIDFILE" && kill -$1 `cat $PIDFILE`
}

start() {
  if [[ -z $MYSQL_OPTS ]]; then 
    HOME=$STALKHOME $DAEMON $DAEMON_OPTS 
  else
    HOME=$STALKHOME $DAEMON $DAEMON_OPTS -- $MYSQL_OPTS
  fi
  return $?
}

stop() {
  if sig TERM; then
    while sig 0 ; do
      echo -n "."
      sleep 1
    done
    return 0
  else
    echo "$DESC is not running." 
    return 1
  fi
}

status() {
  if sig 0 ; then
    echo "$DESC (`cat $PIDFILE`) is running."
    return 0
  else
    echo "$DESC is stopped."
    return 1
  fi
}

case "$1" in
  start)
    echo "Starting $DESC"
  	start
  	if [ $? = 0 ] ; then
        log_success_msg 
        exit 0
    elif [ $? = 1 ] ; then
        log_failure_msg 
        exit 1
    fi
  	;;

  stop)
  	echo "Stopping $DESC"
  	stop
  	if [ $? = 0 ] ; then
        log_success_msg 
        exit 0
    elif [ $? = 1 ] ; then
        log_failure_msg 
        exit 1
    fi
  	;;
  status)
    status ;;

  restart)
    echo "Restarting $DESC"
    stop
    sleep 1
    start
    if [ $? = 0 ] ; then
        log_success_msg 
        exit 0
    elif [ $? = 1 ] ; then
        log_failure_msg 
        exit 1
    fi
    ;;

  *)
    echo "Usage: $0 {start|stop|status|}" >&2
    exit 1
    ;;
esac
